version: '2'
services:
    gallery-app:
        image: gallery
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://gallery-postgresql:5432/gallery
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    gallery-postgresql:
        extends:
            file: postgresql.yml
            service: gallery-postgresql
